//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EIP_DBEntities : DbContext
    {
        public EIP_DBEntities()
            : base("name=EIP_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tApplypunch> tApplypunches { get; set; }
        public virtual DbSet<tBillboard> tBillboards { get; set; }
        public virtual DbSet<tBudget> tBudgets { get; set; }
        public virtual DbSet<tCalendar> tCalendars { get; set; }
        public virtual DbSet<tEmployee> tEmployees { get; set; }
        public virtual DbSet<tIncome> tIncomes { get; set; }
        public virtual DbSet<tLevel> tLevels { get; set; }
        public virtual DbSet<tMetting_date> tMetting_date { get; set; }
        public virtual DbSet<tNotify> tNotifies { get; set; }
        public virtual DbSet<tProject> tProjects { get; set; }
        public virtual DbSet<tProjectDetail> tProjectDetails { get; set; }
        public virtual DbSet<tPunchtime> tPunchtimes { get; set; }
        public virtual DbSet<tSignoff> tSignoffs { get; set; }
        public virtual DbSet<tTeamMember> tTeamMembers { get; set; }
        public virtual DbSet<tTimeRecord> tTimeRecords { get; set; }
        public virtual DbSet<tLeavecount> tLeavecounts { get; set; }
        public virtual DbSet<tleavesort> tleavesorts { get; set; }
        public virtual DbSet<tLeave> tLeaves { get; set; }
        public virtual DbSet<tOvertime> tOvertimes { get; set; }
    }
}
