//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBudget
    {
        public int fBudgetId { get; set; }
        public int fProjectId { get; set; }
        public Nullable<int> fSalaryHour { get; set; }
        public Nullable<double> fManagementFeePct { get; set; }
        public Nullable<int> fBudget { get; set; }
        public Nullable<System.DateTime> fApplydate { get; set; }
        public Nullable<System.DateTime> fPassdate { get; set; }
        public string fagree { get; set; }
    
        public virtual tProject tProject { get; set; }
    }
}
