//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCalendar
    {
        public int fId { get; set; }
        public string fTitle { get; set; }
        public string fContent { get; set; }
        public string fStart { get; set; }
        public string fEnd { get; set; }
        public Nullable<int> fEmployeeId { get; set; }
        public string fSort { get; set; }
        public Nullable<int> fProjectId { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        public virtual tProject tProject { get; set; }
    }
}
