//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIncome
    {
        public int fId { get; set; }
        public int fProjectId { get; set; }
        public string fTaxID { get; set; }
        public string fPaymentStatus { get; set; }
        public double fLevelPCT { get; set; }
        public Nullable<System.DateTime> fInvoiceDate { get; set; }
        public int fAmount { get; set; }
        public double fTaxRate { get; set; }
        public int fTaxPrice { get; set; }
        public int fTotal { get; set; }
        public string fIsPay { get; set; }
        public Nullable<System.DateTime> fPaymentDate { get; set; }
    
        public virtual tProject tProject { get; set; }
    }
}
