//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tLevel()
        {
            this.tProjectDetails = new HashSet<tProjectDetail>();
        }
    
        public int fLevelId { get; set; }
        public int fProjectId { get; set; }
        public string fLevelName { get; set; }
        public Nullable<int> fEstimateTime { get; set; }
        public Nullable<int> fSpendTime { get; set; }
    
        public virtual tProject tProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProjectDetail> tProjectDetails { get; set; }
    }
}
