//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tOvertime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOvertime()
        {
            this.tSignoffs = new HashSet<tSignoff>();
        }
    
        public int fId { get; set; }
        [DisplayName("員工編號")]
        public int fEmployeeId { get; set; }
        [DisplayName("加班類型")]
        public string fSort { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        [DisplayName("申請日期")]
        public System.DateTime fSubmitDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        [DisplayName("生效日期")]
        public System.DateTime fActiveDate { get; set; }

        [DisplayName("時數")]
        public double fTimeCount { get; set; }
        [DisplayName("原因(必填)")]
        public string fReason { get; set; }
        public Nullable<int> fState { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSignoff> tSignoffs { get; set; }
    }
}
