//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSignoff
    {
        public int fId { get; set; }
        public Nullable<int> fLeaveId { get; set; }
        public Nullable<int> fAlpplypunchId { get; set; }
        public Nullable<int> fOvertimeId { get; set; }
        public int fSupervisorId { get; set; }
        public Nullable<int> fIsAgreed { get; set; }
        public string fApplyClass { get; set; }
        public System.DateTime fStartdate { get; set; }
        public Nullable<System.DateTime> fPassdate { get; set; }
        public System.DateTime fEnddate { get; set; }
        public Nullable<int> fRevoke { get; set; }
    
        public virtual tApplypunch tApplypunch { get; set; }
        public virtual tEmployee tEmployee { get; set; }
        public virtual tLeave tLeave { get; set; }
        public virtual tOvertime tOvertime { get; set; }
    }
}
