//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTimeRecord
    {
        public int fTimeRecordId { get; set; }
        public System.DateTime fDate { get; set; }
        public int fEmployeeId { get; set; }
        public int fProjectId { get; set; }
        public int fProjectDetailId { get; set; }
        public int fTime { get; set; }
        public string fApprove { get; set; }
        public string fRemarks { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        public virtual tProject tProject { get; set; }
        public virtual tProjectDetail tProjectDetail { get; set; }
    }
}
